### ISSUE TITLE
CAD Files?

### ISSUE THREAD

**Issue by haitch-dot-tech** [Wh1teRabbitHU/ER-TFT1.69-1_STM32-Driver#1]
Hello @Wh1teRabbitHU,
I am working on my own design of a custom board that happens to use the same screen as this one.
If you use KiCad (like me), would there be any chance that you could provide the symbol, footprint or 3D model files for the display?
Thanks.

**Comment by Wh1teRabbitHU** [comment]
Hi @henryhallau !

For symbol, I was just using a general 01x18 header and I added the pins based on the datasheet.
The footprint is handmade and it works properly. (I recommend 0.8mm PCB, because the flex cable is too short)
I also found a very similar 3D model, but sadly the flex cable part is not fixing properly.

I uploaded all 3 into the design folder, which you can find here: (ER-TFT1_69-1_SMD_18PIN)
https://github.com/Wh1teRabbitHU/ER-TFT1.69-1_STM32-Driver/tree/master/Adapter/Design

Let me know if you have any other questions!

**Comment by haitch-dot-tech** [comment]
Thanks! This will be a great help😜
